name: Digital_$(Date:yyyyMMdd)$(Rev:.r)

trigger:

- main

pool:

  name: 'windows'
  vmImage: 'windows-latest'

 

variables:

  buildPlatform: 'Any CPU'

  buildConfiguration: 'Release'

  solution: '**/*.sln'

  project: '**/DigitalSignature.csproj'

 

steps:

- task: NuGetToolInstaller@1

 

- task: NuGetCommand@2

  inputs:

    restoreSolution: '$(solution)'

 

- task: VSBuild@1

  inputs:

    solution: '$(solution)'

    msbuildArgs: '/peployOnBuild=true /p:WebPublishMethod=Package /packageAsSingleFile=true /p:SkipInvalidConfigurations=true /packageLocation="$(build.artifactStagingDirectory)"'

    platform: '$(buildPlatform)'

    configuration: '$(buildConfiguration)'

 

- task: VSTest@2

  inputs:

    platform: '$(buildPlatform)'

    configuration: '$(buildConfiguration)'

    

- task: PublishBuildArtifacts@1

  inputs:

    pathtoPublish: '$(Build.ArtifactStagingDirectory)'

    artifactName: 'azuredrop'

    publishLocation: 'Container'